### ISSUE TITLE
New languages? 

### ISSUE THREAD

**Issue by decries** [Axel-NCHO/ReddTok#2]
Hi, can you add more languages? Or I can do that myself?

**Comment by Axel-NCHO** [comment]
Hi.  

I noticed that Russian and Deutch languages were suported but not activated, so I activated them by creating the corresponding voice selection methods in VoiceService.cs.  

Feel free to add more languages, but ones will be able to use them only if they are already installed on their machine.

Procedure :  

    -> Add an identifier for the new language in the Language enumeration
    -> Create the corresponding voice selection method in VoiceService.cs
    -> Integrate the new language in AudioFactory.cs.
